TigerMinesweeper: TigerMinesweeper.o
	gcc -o TigerMinesweeper TigerMinesweeper.o
	make clean

TigerMinesweeper.o: TigerMinesweeper.c TigerMinesweeper.h
	gcc -c TigerMinesweeper.c

clean :
	del TigerMinesweeper.o